language: node_js
node_js:
  - "lts/*"
cache: npm

install:
  - "npm install"
script:
  - "npm run build"

branches:
  only:
    - master
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
